name: Publish Font Awesome Icon Pack to Our.Umbraco Package Repository
  
on:
  release:
    types: [published]
 
jobs:
  deploy:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set Version based on tag
      shell: bash
      run: echo ::set-env name=PKG_VERSION::$(basename $GITHUB_REF)
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
     
    - name: Install UmbPack
      run: dotnet tool install --global Umbraco.Tools.Packages
 
    - name: Create the Umbraco Package
      run: umbpack pack package.xml -v ${{ env.PKG_VERSION }}

    - name: Upload to Our Umbraco Package Repository
      run: umbpack push -w v890,v880,v870,v860,v850,v840,v830,v820,v810,v800,v7150,v7140,v7130,v7120,v7110,v7100,v790,v780,v770,v760,v750,v740,v730,v720,v710,v700 -k ${{ secrets.OUR_DEPLOY_KEY }} Font_Awesome_Icon_Pack_${{ env.PKG_VERSION }}.zip
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontAwesomeIconPack
        path: Font_Awesome_Icon_Pack_${{ env.PKG_VERSION }}.zip
